### ISSUE TITLE
Handling of content that requires "explicit size"

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-tabs#9]
# Description

Some polymer components requires to be explicitely sized, like iron-list (see https://github.com/PolymerElements/iron-list#sizing-iron-list).

In order to ease the usage of such components inside cosmoz-tabs, when `cosmoz-tabs` is explicitely sized by mean of `flex` class, it should render the content of `cosmoz-tab` children inside a container that use vertical flexbox.
(but only in standard mode, not accordion).

Assuming `iron-flex-layout-classes` is available, a sample usage would be:

```
<div class="fit vertical layout">
   <cosmoz-tabs class="flex">
      <cosmoz-tab>
         <iron-list class="flex">   
```
When distributed, the `iron-list` component should be inside an explicitely sized container that uses a vertical flexbox. That way, `iron-list` will be explicitely sized.

## Actual outcome

In the demo page, the last demo renders an `iron-list` in the first tab.
However, the `iron-list` component is not rendered within a vertical flexbox, so that it renders all the items instead of only enough items to fill the viewport (in the devtools inspector, check for the children of `<div id="items">` in `iron-list`).

**Comment by megheaiulian** [comment]
@plequang :
Previous behavior of the component used `flex` property/attribute in normal mode to set `flex: 1 1 0.000001px` across DOM until the `cosmoz-tab` children so that everything is distributed into the available space.

I change that to `flex: 1 1 auto`|`--layout-flex-auto` and now if `cosmoz-tabs` has explicit height (doesn't need `flex`|`fit` classes) than `cosmoz-tab` and children will fit only the available space. That is independent of any `flex` or `fit` classes on the parent `cosmoz-tabs`. But if `cosmoz-tabs` doesn't have explicit height than each tab will size itself as needed depending on content.
